In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
data = load_iris()
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [2]:
x = data.data
y = data.target

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=45)

In [4]:
print(x.shape,x_train.shape,x_test.shape)

(150, 4) (112, 4) (38, 4)


In [5]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [6]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,model.predict(x_test))

array([[14,  0,  0],
       [ 0,  9,  0],
       [ 0,  2, 13]], dtype=int64)

In [7]:
confusion_matrix(y_train,model.predict(x_train))

array([[36,  0,  0],
       [ 0, 39,  2],
       [ 0,  2, 33]], dtype=int64)

In [8]:
from sklearn.decomposition import PCA
x_pca = PCA(n_components=2)
x_scaled = x_pca.fit_transform(x)

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.25,random_state=45)

In [10]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,model.predict(x_test))

array([[14,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 15]], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train,model.predict(x_train))

array([[36,  0,  0],
       [ 0, 38,  3],
       [ 0,  4, 31]], dtype=int64)

In [13]:
print(classification_report(y_train,model.predict(x_train)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.90      0.93      0.92        41
           2       0.91      0.89      0.90        35

    accuracy                           0.94       112
   macro avg       0.94      0.94      0.94       112
weighted avg       0.94      0.94      0.94       112



In [14]:
print(classification_report(y_test,model.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        15

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [15]:
from sklearn.datasets import load_digits
data = load_digits()
data.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [18]:
df = pd.DataFrame(data.data,columns=data.feature_names)
df['target'] = data.target

In [60]:
pd.set_option('display.max_columns',None)
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  pixel_1_2  pixel_1_3  \
0           0.0        0.0        0.0        0.0       13.0       15.0   
1           0.0        0.0        0.0        0.0        0.0       11.0   
2           0.0        0.0        0.0        0.0        3.0       16.0   
3           0.0        0.0        0.0        8.0       13.0        6.0   
4           0.0        0.0        0.0        0.0        0.0        7.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        0.0        1.0       16.0       14.0   
1793        1.0        0.0        0.0        0.0       16.0       15.0   
1794        0.0        0.0        0.0        0.0       13.0       16.0   
1795        0.0        0.0        0.0        0.0       14.0       16.0   
1796        0.0        0.0        0.0        2.0       16.0       14.0   

      pixel_1_4  pixel_1_5  pixel_1_6  pixel_1_7  pixel_2_0  pixel_2_1  \
0          10.0       15.0        5.0        0.0        0.0        3.0   
1          16.0        9.0        0.0        0.0        0.0        0.0   
2          15.0       14.0        0.0        0.0        0.0        0.0   
3          15.0        4.0        0.0        0.0        0.0        2.0   
4           8.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792       12.0       16.0        3.0        0.0        0.0        4.0   
1793       12.0       16.0        1.0        0.0        0.0        3.0   
1794        8.0        2.0        1.0        0.0        0.0        0.0   
1795       16.0       15.0        1.0        0.0        0.0        4.0   
1796        6.0        1.0        0.0        0.0        0.0        0.0   

      pixel_2_2  pixel_2_3  pixel_2_4  pixel_2_5  pixel_2_6  pixel_2_7  \
0          15.0        2.0        0.0       11.0        8.0        0.0   
1           3.0       15.0       16.0        6.0        0.0        0.0   
2           8.0       13.0        8.0       16.0        0.0        0.0   
3           1.0       13.0       13.0        0.0        0.0        0.0   
4           1.0       13.0        6.0        2.0        2.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792       16.0        6.0        3.0       16.0        4.0        0.0   
1793       16.0        7.0        0.0       13.0        6.0        0.0   
1794       16.0       15.0       10.0       16.0        5.0        0.0   
1795       16.0        7.0        3.0       16.0        7.0        0.0   
1796       15.0       15.0        8.0       15.0        0.0        0.0   

      pixel_3_0  pixel_3_1  pixel_3_2  pixel_3_3  pixel_3_4  pixel_3_5  \
0           0.0        4.0       12.0        0.0        0.0        8.0   
1           0.0        7.0       15.0       16.0       16.0        2.0   
2           0.0        0.0        1.0        6.0       15.0       11.0   
3           0.0        0.0        2.0       15.0       11.0        1.0   
4           0.0        0.0        7.0       15.0        0.0        9.0   
...   

In [22]:
import warnings
warnings.filterwarnings('ignore')
sns.countplot(df['target'])

<AxesSubplot:xlabel='target', ylabel='count'>

In [26]:
x = data.data
y = data.target

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=458)

In [29]:
print(x.shape,x_train.shape,x_test.shape)

(1797, 64) (1257, 64) (540, 64)


In [30]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [31]:
confusion_matrix(y_test,model.predict(x_test))

array([[57,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0, 48,  0,  0,  0,  0,  0,  0,  2,  1],
       [ 0,  0, 52,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 52,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 50,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0, 59,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  1,  1, 54,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  1,  0, 55,  0,  1],
       [ 0,  1,  1,  0,  0,  1,  0,  1, 52,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 44]], dtype=int64)

In [32]:
confusion_matrix(y_train,model.predict(x_train))

array([[120,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 131,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 125,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 130,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 130,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 122,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 125,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 120,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 118,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 136]], dtype=int64)

In [55]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.99)
x_scaled = pca.fit_transform(x)

In [57]:
x_scaled.shape

(1797, 41)

In [50]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.30,random_state=458)

In [51]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [52]:
confusion_matrix(y_test,model.predict(x_test))

array([[ 8, 19,  2,  0,  1, 15,  3,  9,  1,  0],
       [ 7, 23,  2,  0,  0,  6, 10,  3,  0,  0],
       [ 1,  3, 13,  4,  0,  9,  0,  0,  0, 22],
       [ 0,  0,  2, 35,  0,  3,  0,  0,  0, 13],
       [ 0,  0,  1,  0, 40,  0, 10,  0,  0,  0],
       [ 7,  9,  9,  1,  0, 16,  1,  6,  5,  6],
       [ 0,  4,  0,  0, 14,  0, 38,  0,  0,  0],
       [10, 14,  6,  0,  0, 23,  0,  3,  3,  0],
       [ 6, 16,  9,  0,  0, 16,  1,  5,  0,  3],
       [ 1,  3, 11, 13,  0,  1,  0,  1,  0, 14]], dtype=int64)

In [61]:
from sklearn.datasets import load_digits
ld=load_digits()
ld

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [63]:
x1=ld.data
x1

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [64]:
y1=data.target
y1

array([0, 1, 2, ..., 8, 9, 8])

In [65]:
from sklearn.preprocessing import RobustScaler
rs=RobustScaler()
rs_scaled=rs.fit_transform(x1)

In [66]:
rs_scaled

array([[ 0.        ,  0.        ,  0.125     , ..., -0.5       ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.5       , ...,  0.33333333,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.5       , ...,  0.83333333,
         4.5       ,  0.        ],
       ...,
       [ 0.        ,  0.        , -0.375     , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.25      , ...,  0.5       ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.75      , ...,  0.5       ,
         0.5       ,  0.        ]])

In [67]:
from sklearn.model_selection import train_test_split


In [68]:
x_train,x_test,y_train,y_test=train_test_split(rs_scaled,y1,test_size=0.30,random_state=499)

In [69]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [70]:
model.score(x_test,y_test)

0.95

In [71]:
from sklearn.decomposition import PCA
x1_pca=PCA(0.95)
x1_scaled=x1_pca.fit_transform(x1)

In [73]:
x1_pca.explained_variance_ratio_

array([0.14890594, 0.13618771, 0.11794594, 0.08409979, 0.05782415,
       0.0491691 , 0.04315987, 0.03661373, 0.03353248, 0.03078806,
       0.02372341, 0.02272697, 0.01821863, 0.01773855, 0.01467101,
       0.01409716, 0.01318589, 0.01248138, 0.01017718, 0.00905617,
       0.00889538, 0.00797123, 0.00767493, 0.00722904, 0.00695889,
       0.00596081, 0.00575615, 0.00515158, 0.0048954 ])

In [74]:
x1_pca.n_components_

29

In [76]:
x_train,x_test,y_train,y_test=train_test_split(x1_scaled,y1,test_size=0.30,random_state=499)

In [77]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [78]:
model.score(x_test,y_test)

0.9518518518518518